### ISSUE TITLE
raise IOError ("could not load actor Model %s" % (modelPath)) 

### ISSUE THREAD

**Issue by burnie5749** [fireclawthefox/panda3d-character-controller#1]
When using the character controller it is unable to find the fox model for an unknown reason.
![image](https://user-images.githubusercontent.com/46714025/105716629-03594280-5f17-11eb-823c-d5e5e22fa519.png)
 Those are the errors which I am getting when I try and load the model. There is a better discussion about the issues I am having on [here](https://discourse.panda3d.org/t/extended-character-controller/23770/2) which is the p3d discussion forum. Any help given on this issue would be greatly appreciated

**Comment by fireclawthefox** [comment]
In case anyone is stumbling upon this, having the same error.
Make sure the models or parts of the path reside somewhere on the configured model path using pandas "model-path" config variable.

Further information and discussion can be found here: https://discourse.panda3d.org/t/character-controller-can-not-find-config-json-file/27084
